# Generated by Django 3.2.5 on 2021-07-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
